#!/bin/bash

## script to run feature selection and variance explained pipeline

#!#############################################################
#!#### Modify the options in this section as appropriate ######
#!#############################################################

#! Name of the job:
#SBATCH -J prots_determimants

#! Which project should be charged:
#SBATCH -A MRC-EPID-SL0-CPU

#! How many whole nodes should be allocated?
# In your case you should leave this at 1
#SBATCH --nodes=1

#SBATCH --ntasks=1

#SBATCH --cpus-per-task 16

##SBATCH --exclusive

##SBATCH --nodes=1

#SBATCH --array=1-4979%5

#! Specify required run time
#SBATCH --time=01:00:00

#! What types of email messages do you wish to receive?
#SBATCH --mail-type=FAIL

#SBATCH --output=slurm-%x-%j.out

#! Uncomment this to prevent the job from being requeued (e.g. if
#! interrupted by node failure or system downtime):
##SBATCH --no-requeue

#! Do not change:
#SBATCH -p epid

#! ############################################################
#! Modify the settings below to specify the application's environment, location
#! and launch method:

#! Optionally modify the environment seen by the application
#! (note that SLURM reproduces the environment at submission irrespective of ~/.bashrc):
. /etc/profile.d/modules.sh                # Leave this line (enables the module command)
module purge                               # Removes all modules still loaded
module load rhel7/default-peta4            # REQUIRED - loads the basic environment

#! Insert additional module load commands after this line if needed:

module load gcc/5
module load r-3.6.0-gcc-5.4.0-bzuuksv

## assign directories used for the analysis
DIR=/home/jc2113/rds/rds-rjh234-mrc-epid/Studies/People/Julia/proteome_determinants/bin

cd ${DIR}

## get file name
export FL="${1}"

echo ${FL}

## run as array job
echo "Job ID: $SLURM_ARRAY_TASK_ID"
soma="$(awk -v var="$SLURM_ARRAY_TASK_ID" -F '\t' 'NR == var {print $1}' ${FL})"

echo "Phenotype ${soma}"

#------------------------------#
## -->      run coloc     <-- ##
#------------------------------#

## run proteome determinants R script for each SomaScan protein
1_feature_selection_2_VarExplained.R ${soma}

echo "done"


